spring:
  datasource:
    password: srivatsan
    url: jdbc:mysql://localhost:3306/sys
    username: root

    
  jpa:
    show-sql: true

    hibernate:
      ddl-auto: update

springdoc:
  api-docs:
    path: /myservice      
    
    